=== iMinusMinus/crawler/src/main/resources/schema.json
{
  "$schema":"http://json-schema.org/draft-04/schema#",
  "title": "crawler task definition",
  "description": "crawler task setting and task steps",
  "type": "object",
  "required": ["id", "url", "settings", "steps"],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "url": {
      "type": "string",
      "hint": "if set cookie, please specify url(domain) first"
    },
    "version": {
      "type": "string"
    },
    "settings": {
      "type": "object",
      "required": ["browserName"],
      "properties": {
        "debug": {
          "type": "boolean",
          "hint": "if set true, program exit without quit webdriver"
        },
        "browserName": {
          "type": "string",
          "enum": ["chrome", "msedge", "firefox", "opera", "safari", "internet explorer"]
        },
        "arguments": {
          "type": "array",
          "items": {
            "type": "string",
            "pattern": "^--[a-zA-Z0-9]+=?[a-zA-Z0-9]+$"
          },
          "examples": [
            "--headless=new",
            "--no-sandbox",
            "--remote-allow-origins=*",
            "--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.50",
            "--auto-open-devtools-for-tabs",
            "--disable-blink-features=AutomationControlled"
          ]
        },
        "experimentalOptions": {
          "type": "object",
          "properties": {
            "excludeSwitches": {
              "type": "array",
              "items": {
                "type": "string"
              }
            },
            "mobileEmulation": {
              "type": "object",
              "properties": {
                "deviceName": {
                  "type": "string"
                },
                "userAgent": {
                  "type": "string"
                },
                "deviceMetrics": {
                  "type": "object",
                  "properties": {
                    "width": {
                      "type": "number"
                    },
                    "height": {
                      "type": "number"
                    },
                    "pixelRatio": {
                      "type": "number"
                    }
                  }
                }
              }
            }
          }
        },
        "capabilities": {
          "type": "object",
          "properties": {
            "browserVersion": {
              "type": "string"
            },
            "platformName": {
              "type": "string"
            },
            "goog:chromeOptions": {
              "type": "object"
            }
          }
        }
      }
    },
    "steps": {
      "type": "array",
      "minitems": 1,
      "items": {
        "type": "object",
        "required": ["type"],
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "enum": ["box", "locator", "action", "finder"]
          },
          "target": {
            "type": "string"
          },
          "noPushToContext": {
            "type": "boolean",
            "hint": "when loop elements whether push current item to context or not"
          },
          "hook": {
            "type": "object",
            "properties": {
              "doBefore": {
                "type": "string",
                "hint": "janino script"
              },
              "doAfter": {
                "type": "string",
                "hint": "janino script"
              },
              "doThrowing": {
                "type": "string",
                "hint": "janino script"
              }
            }
          },
          "wrap": {
            "type": "boolean",
            "hint": "wrap item with map if set true"
          },
          "steps": {
            "type": "array"
          },
          "required": {
            "type": "string",
            "hint": "要获取的字段是否必须"
          },
          "xpath": {
            "type": "string",
            "hint": "循环内注意选择器的使用，不要误选择了所有"
          },
          "selector": {
            "type": "string",
            "hint": "循环内注意选择器的使用，不要误选择了所有"
          },
          "escapeScope": {
            "type": "boolean",
            "hint": "sibling may share context, but this step DO NOT use current context scope element"
          },
          "multi": {
            "type": "boolean"
          },
          "valueGetter": {
            "type": "string",
            "enum": ["text", "attribute"]
          },
          "attributeKey": {
            "type": "string"
          },
          "outputPropertyName": {
            "type": "string",
            "pattern": "^[a-zA-Z\\$][0-9a-zA-Z_\\$]+",
            "hint": "'$' stands for root object of result, null stands collection elements"
          },
          "outputValueType": {
            "type": "string",
            "hint": "property type"
          },
          "valueConverter": {
            "type": "janino expression"
          },
          "actionName": {
            "type": "string",
            "enum": ["+cookies", "-cookie", "-cookies","switch", "input", "click", "scroll", "close", "wait", "screenshot"]
          },
          "cookies": {
            "type": "string"
          },
          "cookieNames": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "shortcut": {
            "type": "string",
            "hint": "janino expression for jsoup"
          },
          "inputValue": {
            "type": "string"
          },
          "deltaX": {
            "type": "number"
          },
          "deltaY": {
            "type": "number"
          },
          "scrollTo": {
            "type": "string"
          },
          "minWaitTime": {
            "type": "number"
          },
          "maxWaitTime": {
            "type": "number"
          },
          "expectedCondition": {
            "type": "string"
          },
          "testValue": {
            "type": "string"
          },
          "ignoreNotApply": {
            "type": "boolean",
            "hint": "waiting element might not exist, ignore or throw Timeout exception"
          }
        }
      }
    }
  }
}

=== iMinusMinus/crawler/src/test/resources/dianping_category.json
{
  "id": "dianping-${city}-category",
  "url": "https://www.dianping.com/",
  "settings": {
    "browserName": "chrome",
    "arguments": []
  },
  "steps": [
    {
      "name": "注入cookie",
      "type": "action",
      "actionName": "+cookies",
      "cookies": "${cookie}"
    },
    {
      "id": "locate-city-category",
      "name": "定位当前城市分类",
      "type": "locator",
      "selector": "#cata-hot > div.cata-hot-detail.cata-hot-info > div > a"
    },
    {
      "id": "city-category",
      "name": "点击城市分类",
      "type": "action",
      "actionName": "click",
      "target": "locate-city-category"
    },
    {
      "name": "切换当前城市生活指南地图(含分类、商区/地标/地铁沿线/大学周边)：https://www.dianping.com/shopall/{cityId}/0",
      "type": "action",
      "actionName": "switch",
      "target": "city-category"
    },
    {
      "id": "locate-city-category",
      "name": "定位当前城市分类",
      "type": "locator",
      "selector": "#J-shopall > div > div:nth-child(3) > dl",
      "multi": true
    },
    {
      "id": "get-city-category",
      "name": "获取当前城市分类",
      "type": "box",
      "outputPropertyName": "$",
      "target": "locate-city-category",
      "wrap": true,
      "steps": [
        {
          "name": "获取子行业代码: /{city}/{subIndustry}",
          "selector": "dt > a",
          "type": "finder",
          "outputPropertyName": "subIndustry",
          "valueGetter": "attribute",
          "attributeKey": "href",
          "valueConverter": "arg.substring(arg.lastIndexOf(\"/\") + 1)"
        },
        {
          "name": "获取子行业名称",
          "selector": "dt > a",
          "type": "finder",
          "outputPropertyName": "subIndustryName",
          "valueGetter": "text"
        },
        {
          "id": "locate-category",
          "name": "定位分类",
          "type": "locator",
          "selector": "dd > ul > li",
          "multi": true
        },
        {
          "name": "获取分类信息",
          "type": "box",
          "target": "locate-category",
          "outputPropertyName": "categories",
          "outputValueType": "list",
          "wrap": true,
          "steps": [
            {
              "name": "获取分类名称",
              "type": "finder",
              "selector": "a",
              "outputPropertyName": "categoryName",
              "valueGetter": "text"
            },
            {
              "name": "获取分类代码: //www.dianping.com/{city}/{subIndustry}/{category}",
              "type": "finder",
              "selector": "a",
              "outputPropertyName": "category",
              "valueGetter": "attribute",
              "attributeKey": "href",
              "valueConverter": "arg.substring(arg.lastIndexOf(\"/\") + 1)"
            }
          ]
        }
      ]
    }
  ]
}

=== iMinusMinus/crawler/src/test/resources/dianping_city.json
{
  "id": "dianping-city",
  "url": "https://www.dianping.com/",
  "settings": {
    "browserName": "chrome",
    "device": {
      "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
    },
    "arguments": ["--headless=new", "--no-sandbox"]
  },
  "steps": [
    {
      "name": "注入cookie",
      "type": "action",
      "actionName": "+cookies",
      "cookies": "${cookie}"
    },
    {
      "id": "locate-switch-city",
      "name": "定位更换城市",
      "type": "locator",
      "selector": "#top-nav > div.top-nav-container.clearfix > div.group.J-city-select > a > span.J-city-change"
    },
    {
      "id": "switch-city",
      "name": "切换城市",
      "type": "action",
      "actionName": "click",
      "target": "locate-switch-city"
    },
    {
      "id": "locate-more-city",
      "name": "定位更多城市",
      "type": "locator",
      "selector": "#top-nav > div.top-nav-container.clearfix > div.group.J-city-select > div > a"
    },
    {
      "id": "more-city",
      "name": "选择更多城市",
      "type": "action",
      "actionName": "click",
      "target": "locate-more-city",
      "hint": "navigate to url: https://www.dianping.com/citylist"
    },
    {
      "id": "locate-city-list",
      "name": "定位城市列表",
      "type": "locator",
      "selector": "#main > div.main-citylist > ul > li",
      "multi": true
    },
    {
      "id": "compose-city-list",
      "name": "获取城市列表",
      "type": "box",
      "target": "locate-city-list",
      "outputPropertyName": "$",
      "wrap": false,
      "steps": [
        {
          "id": "locate-more",
          "name": "定位更多：展开按字母排序下该字母开头的所有城市",
          "type": "locator",
          "selector": "span.more"
        },
        {
          "name": "点击更多",
          "type": "action",
          "actionName": "click",
          "target": "locate-more"
        },
        {
          "id": "locate-city",
          "name": "定位城市元素",
          "type": "locator",
          "selector": "div.terms > div > a",
          "multi": true
        },
        {
          "id": "get-city-info",
          "name": "获取城市信息",
          "type": "box",
          "target": "locate-city",
          "wrap": true,
          "steps": [
            {
              "name": "获取城市拼音: //www.dianping.com/{cityPinyinSpelling}/ch0",
              "type": "finder",
              "outputPropertyName": "cityPinyinSpelling",
              "valueGetter": "attribute",
              "attributeKey": "href",
              "valueConverter": "arg.split(\"/\")[3]"
            },
            {
              "name": "获取城市中文名称",
              "type": "finder",
              "outputPropertyName": "cityName",
              "valueGetter": "text"
            },
            {
              "id": "locate-clickable",
              "name": "定位当前元素",
              "type": "locator",
              "xpath": "."
            },
            {
              "id": "city-dianping",
              "name": "点击城市专属页面",
              "type": "action",
              "actionName": "click",
              "target": "locate-clickable"
            },
            {
              "id": "switch-to-city",
              "name": "切换城市专属页面",
              "type": "action",
              "actionName": "switch",
              "target": "city-dianping"
            },
            {
              "name": "获取城市id: https://www.dianping.com/shopall/{cityId}/0",
              "type": "finder",
              "selector": "#cata-hot > div > div > a",
              "outputPropertyName": "cityId",
              "valueGetter": "attribute",
              "attributeKey": "href",
              "valueConverter": "arg.split(\"/\")[4]"
            },
            {
              "name": "关闭城市专属页面",
              "type": "action",
              "actionName": "close",
              "target": "city-dianping"
            }
          ]
        },
        {
          "id": "locate-less-city",
          "name": "定位收起：收起按字母排序下的部分城市",
          "type": "locator",
          "selector": "span.up"
        },
        {
          "name": "收起城市",
          "type": "action",
          "actionName": "click",
          "target": "locate-less-city"
        }
      ]
    }
  ]
}
